---
title: "Helpful Resources & Links"
---

## R Studio

1. **Guide to Using R**  
   A comprehensive guide for R beginners by [Jared Adam](https://www.linkedin.com/in/jared-adam-24b107241/):  
   [One code to rule them all (┛ಠ_ಠ)┛彡O](https://jared-adam-psu.github.io/R-Tutorial-for-Tooker-Lab/)  
   This tutorial helps streamline your R learning process, offering clear steps and examples.

2. **Codecademy: Learn R**  
   A helpful, free interactive tutorial to learn R from the basics:  
   [Learn R with Codecademy](https://www.codecademy.com/learn/learn-r?utm_source=pepperjam&utm_medium=affiliate&utm_term=159404&clickId=4716939938&pj_creativeid=8-12462&pj_publisherid=159404)  
   Start from the ground up and improve your R programming skills with hands-on practice.

3. **R Markdown Documentation**  
   Learn to create professional reports, PDFs, and Word documents directly from R code using R Markdown:  
   [R Markdown Documentation](https://rmarkdown.rstudio.com/lesson-1.html)  
   This resource is great for integrating code with reports and presentations.

4. **R Studio Graphing Notes**  
   A reference for creating visualizations and graphs using R Studio:  
   [R Studio Graphing](https://www.jeffdoser.com/files/for875/_book/)  
   This guide provides a deeper dive into R's graphing capabilities.

## R Statistics
-   [Mixed Effects Models](https://meghan.rbind.io/blog/2022-06-28-a-beginners-guide-to-mixed-effects-models)

## Quarto Website Building

1. **How to Create a Quarto Website**  
   A YouTube tutorial showing how to build a website using RStudio, Quarto, and GitHub Pages. Learn how to integrate Quarto with GitHub Pages to host your site.
   <a href="https://youtu.be/YN75YXaLFGM?si=RyCG23IMBwFUKsO8" target="_blank">How to Create a Web Site Using Quarto, RStudio, and GitHub Pages</a>  
   
   <iframe width="560" height="315" src="https://www.youtube.com/embed/YN75YXaLFGM" frameborder="0" allowfullscreen></iframe>
2. Gallery showing different options for formatting a Quarto website: [Quarto Gallery](https://quarto.org/docs/gallery/)
3. Quarto documentation showing how to do a lot of the basics including website navigation, website search, and website tools: <a href="https://quarto.org/docs/websites/" target="_blank">Quarto - Creating a Website</a>

## GitHub

-   A guide to using GitHub created by [Callum Arnold](https://www.linkedin.com/in/arnold-c/){style="text-decoration: none;"}: <a href="https://psu-git.callumarnold.com" target="_blank">Introduction to Git and GitHub</a>

## Citations

1. **Zotero Citations Repository**  
   A collection of citation styles for use with Zotero, a free tool for managing references:  
   [Zotero Citations Repository](https://www.zotero.org/styles)  
   Use this to manage and generate citations for your research papers.

## Other 
1. **<a href="https://youtu.be/65MAB0qRtAE?si=beO8jD5t5SOJzooF" target="_blank">Gallatin Watershed Volunteering Video</a>**  
   Gracea and I volunteered a park near our house to plant trees. You can see us in the back of the video at <a href="https://youtu.be/65MAB0qRtAE?t=42" target="_blank">0:43</a>!  
    

2. **<a href="https://www.iwillteachyoutoberich.com/c-conscious-spending-plan/" target="_blank">Concious Spending Plan</a>**  
   A guide to creating a personal financial plan that prioritizes essential spending and savings. It is a useful resource for developing a budget that reflects your personal financial goals.
